#!/usr/xbin/bash
 a="\033[30;1m"
 m="\033[31;1m"
 h="\033[32;1m"
 k="\033[33;1m"
 b="\033[34;1m"
 c="\033[35;1m"
 pu="\033[36;1m"
 p="\033[37;1m"
 m1="\033[38;1m"
 p2="\033[39;1m"
 hi="\033[40;1m"
 clear
 s="\033[31;1m╔"
 t="\033[31;1m╗"
 u="\033[31;1m║"
 z="${m}════════════════════════════════"
 q="${m}════"
 j="${m}══════════"
 o="${m}╚"
 n="${m}╝"
 ulang="sh spam-sms.sh"
clear
echo "   ${s}${z}${t}"
echo "\033[031m   _________________      _____   .___ "
echo "\033[031m  /   _____/\_____  \    /     \  |   |"
echo "\033[032m  \_____  \  /   |   \  /  \ /  \ |   |"
echo "\033[032m  /        \/    |    \/    Y    \|   |"
echo "\033[033m /_______  /\_______  /\____|__  /|___|"
echo "\033[033m         \/         \/         \/      "
echo "   ${o}${z}${n}"
echo
echo "\033[037m     ▇▇\033[032m▇▇▇▇▇▇\033[033m ____ ___ ____ ____ "
echo "\033[037m     ▇▇\033[032m▇▇▇\033[037m☪\033[032m▇▇\033[036m [__   |  |__| |__/ "
echo "\033[037m     ▇▇\033[032m▇▇▇▇▇▇\033[034m ___]  |  |  | |  \ "
echo "\033[037m    │"
echo "\033[037m    │"
echo "\033[037m    ┴"

echo "\033[034m  LOVE PAKISTAN AM BRAND BOY"
echo "${k}<═════════════════════════════════════════════>"
echo "${p}[${h}01${p}] ${h}═══>   MY PERSONAL${p}「1」"
echo "${p}[${h}00${p}] ${m}═══> CLOSE YOUR PROGRAM"
echo "${k}<═════════════════════════════════════════════>"
echo
echo "${p}"
echo "\033[037m"
read -p ">> " pilih;
if [ $pilih = "1" ]:
then
   echo "installing..."
   sleep 1
   cd tool
   python2 encript-python-v2.py,
echo
echo "${s}${z}${t}"
echo "\033[39;1m[\033[32;1m√\033[39;1m]\033[33;1m✯「FINISH」"
echo "\033[39;1m[\033[32;1m√\033[39;1m]\033[35;1m✯「NOW COPY」"
echo "\033[39;1m[\033[32;1m√\033[39;1m]\033[34;1m✯「SHARE WHATSAAP 」"
echo "\033[39;1m[\033[32;1m√\033[39;1m]\033[36;1m✯「SOMI BRAND BOY 」"
echo "${o}${z}${n}"
echo "${p}"
read -p "[+]「BACK」 y/t : " k
if [ $k = y ] || [ $k = Y ];then
sh virus.sh

elif [ $k = t ] || [ $k = T ];then
sh hek.sh
fi

elif [ $r = 06 ] || [ $r = 6 ];then
sh hek.sh

elif [ $r = 00 ] || [ $r = 0 ];then
sleep 1
echo "${b} Thanks You *_*"
exit

else 
echo
echo "${h}         ~ ~  ┌${p1}∩${h}┐${k}(${m}◣${p1}_${m}◢${k})${h}┌${p1}∩${h}┐  ~ ~"
echo "         ${p}[${m}!${p}]${m} WRONG CHOICE ${p}[${m}!${p}]${k}"
echo
sleep 1
sh virus.sh
fi
